# Generated by Django 4.2.13 on 2024-06-23 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_stripe_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlibrary',
            old_name='Course_Product',
            new_name='courses',
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
