# Generated by Django 4.2.13 on 2024-06-23 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_course_product_userlibrary_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
